version: "3.8"

services:
    auth_service:
        build: ./auth_service
        container_name: auth_service
        ports:
            - "8001:8000"

    user_service:
        build: ./user_service
        container_name: user_service
        ports:
            - "8002:8000"

    post_service:
        build: ./post_service
        container_name: post_service
        ports:
            - "8003:8000"
