services:
    auth_service:
        image: auth_service:1.0
        container_name: auth_service
        ports:
            - "8001:8000"
        env_file:
            - .env
        networks:
            - app_network

    user_service:
        image: user_service:1.0
        container_name: user_service
        ports:
            - "8002:8000"
        env_file:
            - .env
        depends_on:
            - auth_service
        networks:
            - app_network

    post_service:
        image: post_service:1.0
        container_name: post_service
        ports:
            - "8003:8000"
        env_file:
            - .env
        depends_on:
            - auth_service
            - user_service
        networks:
            - app_network

    message_service:
        image: message_service:1.0
        container_name: message_service
        ports:
            - "8005:8000"
        env_file:
            - .env
        networks:
            - app_network

    messaging_service:
        image: ws_messaging_service:1.0
        container_name: ws_messaging_service
        ports:
            - "8004:8000"
        env_file:
            - .env
        depends_on:
            - message_service
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
